site_name: FAIR-by-Design Template Repository
docs_dir: resources
theme:
  name: material
  palette:
    primary: custom
  logo: attachments/logo-white.png
  custom_dir: resources/overrides
  features:
    - navigation.footer
    - search.highlight
    - search.suggest
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - md_in_html
plugins:
  - search
  - tags
  - mike:
      version_selector: true
  - exclude:
      glob:
        - "*Activities/*"
        - "*Assessment/*"
        - "*Templates/*"
        - "*Feedback/*"
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
        - "*.pptx"
        - "*_plan.md"
        - "*_facilitator_guide.md"
        - "*syllabus.md"
      regex:
        - '.*\.(tmp|bin|tar)$'
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
citation:
  cff-version: 1.2.0
  message: "If you use these learning materials, please cite it as below."
  authors:
    - family-names: Filiposka
      given-names: Sonja
      orcid: https://orcid.org/0000-0003-0034-2855
      affiliation: UKIM
  title: "ATRIUM Training: FAIR-by-Design Methodology for learning materials"
  abstract: "Two-session training for the ATRIUM community on how to implement the FAIR-by-Design methodology developed by the SKills4EOSC project."
  version: 1.0.0
  doi: 10.5070/zenodo.123
  date-released: "2025"
  license: CC-BY-4.0
  license-url: "https://creativecommons.org/licenses/by/4.0/legalcode.txt"
  type: generic
  keywords:
    - "FAIR-by-Design"
    - "learning materials"
    - "methodology"
  repository: "https://github.com/FAIR-by-Design-Methodology/ATRIUM"
signposting_linkset: https://raw.githubusercontent.com/FAIR-by-Design-Methodology/ATRIUM/main/linkset.json # do not update manually
signposting_default_profile: '' # update with an URL towards the profile used for the Markdown pages (optional)
# signposting_gitbook_url: https://gitbook.example.com # leave commented (prefixed with `#`) if using GitHub Pages with the default domain.
signposting_exclusions:
  - 'venv/**'
  - 'external-resources/**'
  - 'Feedback/**'
  - '**/Activities/**'
  - '*/Assessment/**'
  - 'index.md'
  - '02 process_description.md'
  - '03 glossary.md'
  - 'template_unit_lesson_plan.md'
  - '**/*facilitator_guide.md'
  - '*syllabus.md'
  - '**/*_plan.md'
  - '**/template_content.md'
